import { z } from 'zod';
const id = z.string().min(1).max(200);
const num = z.number().finite().nonnegative();
export const exerciseSchema = z.object({id,name:z.string().min(1).max(120),muscle:z.string().min(1).max(60),secondary:z.string().max(150),equipment:z.string().min(1).max(60),notes:z.string().max(2000)});
export const planSchema = z.object({id,exerciseId:id,alternativeExerciseIds:z.array(id).max(8).optional(),sets:z.number().int().min(1).max(12),minReps:z.number().int().min(1).max(100),maxReps:z.number().int().min(1).max(100),rest:z.number().int().min(0).max(900),notes:z.string().max(2000),targetType:z.enum(['reps','minutes','seconds','meters','instruction']).optional(),targetText:z.string().max(120).optional(),suggestedWeight:num.max(2000).nullable().optional(),loadText:z.string().max(120).optional()}).refine(p=>p.maxReps>=p.minReps,{message:'A faixa máxima deve ser maior ou igual à mínima.'}).refine(p=>!p.alternativeExerciseIds?.includes(p.exerciseId),{message:'O exercício principal não pode ser uma alternativa.'});
export const routineSchema = z.object({id,name:z.string().min(1).max(80),description:z.string().max(180),days:z.array(z.number().int().min(0).max(6)).max(7),exercises:z.array(planSchema).max(40),color:z.enum(['lime','purple','blue','amber'])});
export const setSchema = z.object({id,weight:num.max(2000).nullable(),reps:z.number().int().min(0).max(1000).nullable(),rir:z.number().min(0).max(4).nullable(),rpe:z.number().min(1).max(10).nullable(),type:z.enum(['normal','warmup','backoff','drop']),status:z.enum(['pending','completed','skipped']),notes:z.string().max(1000),completedAt:z.string().nullable()}).refine(s=>s.status!=='completed'||(s.weight!==null&&s.reps!==null&&s.reps>0),{message:'Preencha carga e repetições antes de concluir a série.'});
export const sessionExerciseSchema=z.object({id,exercise:exerciseSchema,plan:planSchema,sets:z.array(setSchema).max(20)});
export const sessionSchema=z.object({id,routineId:id.nullable(),name:z.string().min(1).max(80),startedAt:z.string().datetime(),finishedAt:z.string().datetime().nullable(),status:z.enum(['planned','active','completed','cancelled']),notes:z.string().max(2000),isDemo:z.boolean(),exercises:z.array(sessionExerciseSchema).max(40)}).refine(s=>s.status!=='completed'||(s.finishedAt!==null&&s.exercises.some(e=>e.sets.some(x=>x.status==='completed'))),{message:'Conclua ao menos uma série.'});
export const profileSchema=z.object({id,name:z.string().min(1).max(80),height:num.max(250).nullable(),weight:num.max(500).nullable().optional(),goals:z.array(z.string().max(100)).min(1).max(5),unit:z.enum(['kg','lb']),rest:z.number().int().min(0).max(900),theme:z.enum(['dark','light']),onboarded:z.boolean(),weeklyGoal:z.number().int().min(1).max(7),todayChoice:z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),routineId:id.nullable()}).optional()});
export const measurementSchema=z.object({id,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),weight:num.max(500).nullable(),waist:num.max(300).nullable(),chest:num.max(300).nullable(),arm:num.max(150).nullable(),thigh:num.max(200).nullable(),hip:num.max(300).nullable()}).refine(m=>[m.weight,m.waist,m.chest,m.arm,m.thigh,m.hip].some(v=>v!==null),{message:'Preencha pelo menos uma medida.'});
export type Exercise=z.infer<typeof exerciseSchema>;
export type Plan=z.infer<typeof planSchema>;
export type Routine=z.infer<typeof routineSchema>;
export type WorkoutSet=z.infer<typeof setSchema>;
export type SessionExercise=z.infer<typeof sessionExerciseSchema>;
export type Session=z.infer<typeof sessionSchema>;
export type Profile=z.infer<typeof profileSchema>;
export type Measurement=z.infer<typeof measurementSchema>;
export type Resource='profile'|'exercise'|'routine'|'session'|'measurement';
export type Entity=Profile|Exercise|Routine|Session|Measurement;
export type FitnessData={profile:Profile;exercises:Exercise[];routines:Routine[];sessions:Session[];measurements:Measurement[];versions:Record<string,number>};
export const fitnessDataSchema=z.object({profile:profileSchema,exercises:z.array(exerciseSchema),routines:z.array(routineSchema),sessions:z.array(sessionSchema),measurements:z.array(measurementSchema),versions:z.record(z.string(),z.number())});
export const resourceSchemas={profile:profileSchema,exercise:exerciseSchema,routine:routineSchema,session:sessionSchema,measurement:measurementSchema};
export const newId=()=>crypto.randomUUID();
