import type {Exercise,FitnessData,Routine,Session} from './model';
const rows=[
['Supino reto com barra','Peito','Barra','Ombros, Tríceps'],['Supino inclinado com halteres','Peito','Halteres','Ombros, Tríceps'],['Crucifixo na máquina','Peito','Máquina',''],['Crossover','Peito','Cabo','Ombros'],['Puxada alta','Costas','Cabo','Bíceps, Costas médias, Ombros'],['Remada baixa','Costas','Cabo','Bíceps, Dorsais, Ombros'],['Remada unilateral','Costas','Halteres','Bíceps, Dorsais, Ombros'],['Remada na máquina','Costas','Máquina','Dorsais'],['Desenvolvimento com halteres','Ombros','Halteres','Tríceps'],['Elevação lateral','Ombros','Halteres',''],['Crucifixo inverso','Ombros','Máquina',''],['Rosca direta','Bíceps','Barra','Antebraços'],['Rosca alternada','Bíceps','Halteres','Antebraços'],['Rosca martelo','Bíceps','Halteres','Antebraços'],['Tríceps pulley','Tríceps','Cabo',''],['Tríceps francês','Tríceps','Halteres',''],['Tríceps testa','Tríceps','Barra',''],['Agachamento livre','Quadríceps','Barra','Panturrilhas, Glúteos, Posteriores, Lombar'],['Leg press','Quadríceps','Máquina','Panturrilhas, Glúteos, Posteriores'],['Cadeira extensora','Quadríceps','Máquina',''],['Mesa flexora','Posteriores','Máquina',''],['Cadeira flexora','Posteriores','Máquina',''],['Stiff','Posteriores','Barra','Glúteos, Lombar'],['Levantamento romeno','Posteriores','Halteres','Glúteos, Lombar'],['Elevação pélvica','Glúteos','Barra','Panturrilhas, Posteriores'],['Panturrilha sentado','Panturrilhas','Máquina',''],['Panturrilha em pé','Panturrilhas','Máquina',''],['Abdominal no cabo','Abdômen','Cabo',''],['Abdominal solo','Abdômen','Peso corporal',''],['Rosca de punho','Antebraços','Halteres',''],['Agachamento no smith','Quadríceps','Smith machine','Panturrilhas, Glúteos, Posteriores, Lombar']];
export const library:Exercise[]=rows.map(([name,muscle,equipment,secondary],i)=>({id:`base-${i}`,name,muscle,equipment,secondary,notes:''}));
export function initialData(uid:string):FitnessData{
 const combos=[[0,4,5,9,11,14],[18,23,19,21,26,28],[1,7,8,10,13,16],[17,20,24,25,27]];
 const routines:Routine[]=combos.map((ids,i)=>({id:`${uid}:routine-${i}`,name:['Upper A','Lower A','Upper B','Lower B'][i],description:i%2?'Quadríceps · Posteriores · Glúteos':'Peito · Costas · Ombros · Braços',days:[[1],[2],[4],[5]][i],color:(['lime','purple','blue','amber'] as const)[i],exercises:ids.map((n,j)=>({id:`plan-${i}-${j}`,exerciseId:`base-${n}`,sets:3,minReps:8,maxReps:12,rest:j<3?120:60,notes:''}))}));
 const sessions:Session[]=[];
 for(let i=0;i<12;i++){const routine=routines[i%4];const date=new Date();date.setDate(date.getDate()-Math.floor((12-i)*1.8));date.setHours(21,0,0,0);const weights=routine.name.startsWith('Upper')?[35,40,30,6,12,15]:[70,24,25,30,25,0];const startedAt=date.toISOString();sessions.push({id:`${uid}:demo-${i}`,routineId:routine.id,name:routine.name,startedAt,finishedAt:new Date(date.getTime()+(48+i%4*4)*60000).toISOString(),status:'completed',notes:'Sessão fictícia para demonstrar a evolução.',isDemo:true,exercises:routine.exercises.map((p,j)=>({id:`demo-ex-${i}-${j}`,exercise:library.find(x=>x.id===p.exerciseId)!,plan:p,sets:Array.from({length:3},(_,k)=>({id:`demo-set-${i}-${j}-${k}`,weight:weights[j]+(j<3?Math.floor(i/4)*2.5:0),reps:12-k,rir:2,rpe:null,type:'normal' as const,status:'completed' as const,notes:'',completedAt:startedAt}))}))});}
 return {profile:{id:uid,name:'Ismael',height:175,goals:['Perder gordura','Ganhar massa'],unit:'kg',rest:90,theme:'dark',onboarded:false,weeklyGoal:4},exercises:[],routines,sessions,measurements:[],versions:{}};
}
