import type {Exercise,FitnessData} from './model';
const rows=[
['Supino reto com barra','Peito','Barra','Ombros, Tríceps'],['Supino inclinado com halteres','Peito','Halteres','Ombros, Tríceps'],['Crucifixo na máquina','Peito','Máquina',''],['Crossover','Peito','Cabo','Ombros'],['Puxada alta','Costas','Cabo','Bíceps, Costas médias, Ombros'],['Remada baixa','Costas','Cabo','Bíceps, Dorsais, Ombros'],['Remada unilateral','Costas','Halteres','Bíceps, Dorsais, Ombros'],['Remada na máquina','Costas','Máquina','Dorsais'],['Desenvolvimento com halteres','Ombros','Halteres','Tríceps'],['Elevação lateral','Ombros','Halteres',''],['Crucifixo inverso','Ombros','Máquina',''],['Rosca direta','Bíceps','Barra','Antebraços'],['Rosca alternada','Bíceps','Halteres','Antebraços'],['Rosca martelo','Bíceps','Halteres','Antebraços'],['Tríceps pulley','Tríceps','Cabo',''],['Tríceps francês','Tríceps','Halteres',''],['Tríceps testa','Tríceps','Barra',''],['Agachamento livre','Quadríceps','Barra','Panturrilhas, Glúteos, Posteriores, Lombar'],['Leg press','Quadríceps','Máquina','Panturrilhas, Glúteos, Posteriores'],['Cadeira extensora','Quadríceps','Máquina',''],['Mesa flexora','Posteriores','Máquina',''],['Cadeira flexora','Posteriores','Máquina',''],['Stiff','Posteriores','Barra','Glúteos, Lombar'],['Levantamento romeno','Posteriores','Halteres','Glúteos, Lombar'],['Elevação pélvica','Glúteos','Barra','Panturrilhas, Posteriores'],['Panturrilha sentado','Panturrilhas','Máquina',''],['Panturrilha em pé','Panturrilhas','Máquina',''],['Abdominal no cabo','Abdômen','Cabo',''],['Abdominal solo','Abdômen','Peso corporal',''],['Rosca de punho','Antebraços','Halteres',''],['Agachamento no smith','Quadríceps','Smith machine','Panturrilhas, Glúteos, Posteriores, Lombar'],
['Corrida leve','Cardio','Esteira ou rua','Pernas, Coração'],['Corrida intervalada','Cardio','Esteira ou rua','Pernas, Coração'],['Caminhada rápida','Cardio','Esteira ou rua','Pernas, Coração'],['Bicicleta ergométrica','Cardio','Bicicleta','Pernas, Coração'],['Elíptico','Cardio','Elíptico','Pernas, Coração'],['Remo ergométrico','Cardio','Remo','Costas, Pernas, Coração'],['Agachamento com peso corporal','Quadríceps','Peso corporal','Glúteos, Posteriores'],['Flexão de braços','Peito','Peso corporal','Tríceps, Ombros'],['Afundo com halteres','Quadríceps','Halteres','Glúteos, Posteriores'],['Prancha frontal','Abdômen','Peso corporal','Ombros, Lombar'],['Ponte de glúteos','Glúteos','Peso corporal','Posteriores'],
['Supino inclinado na máquina','Peito','Máquina','Ombros, Tríceps'],['Desenvolvimento de ombros na máquina','Ombros','Máquina','Tríceps'],['Remada com apoio','Costas','Máquina','Bíceps, Ombros'],['Extensão de quadril no cabo','Glúteos','Cabo','Posteriores'],['Abdômen na máquina','Abdômen','Máquina',''],['Crossover baixo para alto','Peito','Cabo','Ombros'],['Cadeira abdutora','Glúteos','Máquina',''],['Chest press','Peito','Máquina','Ombros, Tríceps'],['Panturrilhas na máquina','Panturrilhas','Máquina',''],['Futebol','Cardio','Campo','Pernas, Coração'],['Bike','Cardio','Bicicleta','Pernas, Coração'],['Remador','Cardio','Remo','Costas, Pernas, Coração']];
export const library:Exercise[]=rows.map(([name,muscle,equipment,secondary],i)=>({id:`base-${i}`,name,muscle,equipment,secondary,notes:''}));
export function initialData(uid:string,name='Atleta'):FitnessData{
 return {profile:{id:uid,name,height:null,weight:null,goals:[],unit:'kg',rest:90,theme:'dark',onboarded:false,weeklyGoal:4},exercises:[],routines:[],sessions:[],measurements:[],versions:{}};
}
