'use client';
import {useState,type FormEvent} from 'react';
import {ArrowRight,Check,Cloud,Database,KeyRound,LockKeyhole,ShieldCheck,UserPlus} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';

type Mode='login'|'signup'|'reset';
const content={
 login:{eyebrow:'BEM-VINDO DE VOLTA',title:'Entre no seu espaço',description:'Use seu e-mail e senha para acessar treinos, cargas e histórico com segurança.',action:'Entrar',icon:LockKeyhole},
 signup:{eyebrow:'COMECE AGORA',title:'Crie sua conta',description:'Crie seu acesso pessoal. Seus dados ficam separados dos registros de outros usuários.',action:'Criar conta',icon:UserPlus},
 reset:{eyebrow:'RECUPERAR ACESSO',title:'Esqueceu sua senha?',description:'Informe seu e-mail e enviaremos um link seguro para criar uma nova senha.',action:'Enviar link de recuperação',icon:KeyRound}
} as const;

export function AccessGate(){
 const [mode,setMode]=useState<Mode>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const selected=content[mode];const Icon=selected.icon;
 const changeMode=(next:Mode)=>{setMode(next);setError('');setMessage('');};
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{const supabase=createClient();if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;window.location.assign('/');return;}if(mode==='signup'){const {error}=await supabase.auth.signUp({email,password,options:{data:{name:name.trim()}}});if(error)throw error;setMessage('Conta criada. Confira seu e-mail para confirmar o cadastro.');}else{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/reset-password`});if(error)throw error;setMessage('Link enviado. Confira sua caixa de entrada e o spam.');}}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível concluir. Tente novamente.');}finally{setBusy(false);}};
 return <main className="access-page"><section className="access-story"><div className="access-brand"><span><LockKeyhole size={24}/></span><strong>personal<br/>fitness<i>.</i></strong></div><div className="access-copy"><p className="eyebrow">SEU TREINO. SEUS DADOS.</p><h1>Evolua sem perder o histórico.</h1><p>Organize sua rotina, troque exercícios quando precisar e acompanhe carga, volume e progresso em um só lugar.</p><ul><li><Check size={17}/>Treinos e cargas sincronizados</li><li><Check size={17}/>Dados disponíveis no seu aparelho</li><li><Check size={17}/>Acesso protegido pela sua conta</li></ul></div><div className="access-security"><ShieldCheck size={18}/><span>Seus registros são vinculados somente à sua conta.</span></div></section><section className="access-panel"><form className="access-card" onSubmit={submit}><div className="access-tabs" role="tablist" aria-label="Opções de acesso"><button type="button" role="tab" aria-selected={mode==='login'} className={mode==='login'?'active':''} onClick={()=>changeMode('login')}>Entrar</button><button type="button" role="tab" aria-selected={mode==='signup'} className={mode==='signup'?'active':''} onClick={()=>changeMode('signup')}>Criar conta</button></div><div className="access-icon"><Icon size={24}/></div><p className="eyebrow">{selected.eyebrow}</p><h2>{selected.title}</h2><p className="access-description">{selected.description}</p><div className="access-fields">{mode==='signup'&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required maxLength={80} placeholder="Como quer ser chamado?"/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required placeholder="voce@exemplo.com"/></label>{mode!=='reset'&&<label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={6} placeholder="Mínimo de 6 caracteres"/></label>}</div>{error&&<p className="access-feedback error" role="alert">{error}</p>}{message&&<p className="access-feedback success" role="status">{message}</p>}<button className="primary access-action" type="submit" disabled={busy}>{busy?'Aguarde...':selected.action}<ArrowRight size={18}/></button>{mode==='login'&&<button type="button" className="access-forgot" onClick={()=>changeMode('reset')}>Esqueceu a senha?</button>}{mode==='signup'&&<p className="access-switch">Já possui conta? <button type="button" onClick={()=>changeMode('login')}>Entrar</button></p>}{mode==='reset'&&<button type="button" className="access-forgot" onClick={()=>changeMode('login')}>Voltar para entrar</button>}<div className="access-assurance"><span><Cloud size={15}/>Sincronização segura</span><span><Database size={15}/>Histórico preservado</span></div></form></section></main>;
}
