'use client';
import {useState} from 'react';
import {Play,Video,Zap} from 'lucide-react';
import type {Exercise} from '@/lib/fitness/model';

type VideoItem={id:string;title:string};
const videos:Record<string,VideoItem>={
 'base-0':{id:'WPM5e8Xv69A',title:'Como executar o supino com barra'},'base-1':{id:'bH_T3ibPPzg',title:'Supino inclinado com halteres'},'base-2':{id:'dY4LduyY8H0',title:'Crucifixo e crucifixo inverso na máquina'},'base-4':{id:'hWaFwpJieMs',title:'Como executar a puxada alta'},'base-6':{id:'r4-3p0KgEA8',title:'Remada unilateral com halter'},'base-8':{id:'C0We_bEyxlM',title:'Desenvolvimento sentado com halteres'},'base-9':{id:'TOKQbh6FPkU',title:'Como executar a elevação lateral'},'base-10':{id:'EA3q82Yds30',title:'Como executar o crucifixo inverso'},'base-11':{id:'ZoZTBY008V4',title:'Como executar a rosca direta'},'base-12':{id:'WFUJLA89r3g',title:'Rosca com rotação dos halteres'},'base-13':{id:'tvRlfjjH5NA',title:'Como executar a rosca martelo'},'base-14':{id:'RNxRoMP6r4M',title:'Como executar o tríceps na polia'},'base-16':{id:'ot0OGphP5KE',title:'Como executar o tríceps testa'},'base-17':{id:'NcMEyM7qyuk',title:'Como executar o agachamento com barra'},'base-18':{id:'RaI6ofF2geQ',title:'Como executar o leg press'},'base-19':{id:'AuPGdqQ_RIs',title:'Como executar a cadeira extensora'},'base-20':{id:'KXYwW0v9gpM',title:'Como executar a mesa flexora'},'base-22':{id:'PIt6QP_Dcf8',title:'Erros comuns no stiff'},'base-23':{id:'qWb5Zr98B-M',title:'Como executar o levantamento romeno'},'base-24':{id:'-fsi3-u_kao',title:'Como executar a elevação pélvica com barra'},'base-28':{id:'QSkX3gA8cd0',title:'Como executar o abdominal no solo'}
};

export const exerciseDemoIds:Record<string,string>={
 'base-0':'Barbell_Bench_Press_-_Medium_Grip','base-1':'Incline_Dumbbell_Press','base-2':'Butterfly','base-3':'Cable_Crossover','base-4':'Wide-Grip_Lat_Pulldown','base-5':'Seated_Cable_Rows','base-6':'One-Arm_Dumbbell_Row','base-7':'Leverage_High_Row','base-8':'Dumbbell_Shoulder_Press','base-9':'Side_Lateral_Raise','base-10':'Reverse_Machine_Flyes','base-11':'Barbell_Curl','base-12':'Alternate_Incline_Dumbbell_Curl','base-13':'Hammer_Curls','base-14':'Triceps_Pushdown','base-15':'Standing_Dumbbell_Triceps_Extension','base-16':'Lying_Triceps_Press','base-17':'Barbell_Squat','base-18':'Leg_Press','base-19':'Leg_Extensions','base-20':'Lying_Leg_Curls','base-21':'Seated_Leg_Curl','base-22':'Stiff-Legged_Barbell_Deadlift','base-23':'Stiff-Legged_Dumbbell_Deadlift','base-24':'Barbell_Hip_Thrust','base-25':'Seated_Calf_Raise','base-26':'Standing_Calf_Raises','base-27':'Cable_Crunch','base-28':'Crunches','base-29':'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench','base-30':'Smith_Machine_Squat',
 'base-37':'Bodyweight_Squat','base-38':'Pushups','base-39':'Dumbbell_Lunges','base-40':'Plank',
 'base-42':'Leverage_Incline_Chest_Press','base-43':'Leverage_Shoulder_Press','base-44':'Leverage_High_Row','base-47':'Low_Cable_Crossover','base-48':'Thigh_Abductor','base-49':'Leverage_Chest_Press',
 'base-54':'Cable_Seated_Lateral_Raise','base-57':'Reverse_Machine_Flyes','base-58':'Cable_Rear_Delt_Fly','base-59':'Reverse_Flyes','base-60':'Barbell_Shoulder_Press','base-61':'Dumbbell_One-Arm_Shoulder_Press',
 'base-62':'Dumbbell_Bench_Press','base-63':'Leverage_Incline_Chest_Press','base-64':'Standing_Biceps_Cable_Curl'
};
const source='https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';
const frame=(id:string,index:number)=>`${source}/${id}/${index}.jpg`;

function MuscleActivation({exercise}:{exercise:Exercise}){
 const secondary=exercise.secondary.split(',').map(item=>item.trim()).filter(Boolean);
 return <div className="muscle-activation"><div><Zap size={16}/><span><small>Músculo principal</small><strong>{exercise.muscle}</strong></span></div>{secondary.length>0&&<div className="secondary-muscles"><small>Também ativa</small><span>{secondary.map(muscle=><b key={muscle}>{muscle}</b>)}</span></div>}</div>;
}

export function ExerciseMedia({exercise,compact=false}:{exercise:Exercise;compact?:boolean}){
 const [videoOpen,setVideoOpen]=useState(false);const demo=exerciseDemoIds[exercise.id];const video=videos[exercise.id];
 return <div className={`exercise-media ${compact?'compact':''}`}><MuscleActivation exercise={exercise}/>{demo&&<figure className="motion-demo"><div className="motion-frames" aria-label={`Demonstração curta de ${exercise.name}`}><img src={frame(demo,0)} alt={`Posição inicial de ${exercise.name}`} loading="lazy" decoding="async"/><img src={frame(demo,1)} alt={`Posição final de ${exercise.name}`} loading="lazy" decoding="async"/><span>DEMONSTRAÇÃO EM LOOP</span></div><figcaption><span><strong>Execução rápida</strong><small>Posição inicial e final · Free Exercise DB</small></span>{video&&<button type="button" className="secondary" onClick={()=>setVideoOpen(!videoOpen)}><Video size={16}/>{videoOpen?'Fechar vídeo':'Ver mini vídeo'}</button>}</figcaption></figure>}{videoOpen&&video&&<div className="exercise-video"><iframe src={`https://www.youtube-nocookie.com/embed/${video.id}?autoplay=1&rel=0`} title={video.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div>}{!demo&&!video&&<div className="exercise-media-unavailable"><Video size={16}/><span>Adicione uma mídia a este exercício personalizado.</span></div>}{!demo&&video&&!videoOpen&&<button type="button" className="exercise-media-cover" onClick={()=>setVideoOpen(true)} aria-label={`Ver demonstração de ${exercise.name}`}><img src={`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`} alt={`Prévia da execução de ${exercise.name}`}/><span className="media-play"><Play size={20} fill="currentColor"/></span><span className="media-caption"><strong>Ver demonstração</strong><small>O vídeo abre dentro do app</small></span></button>}</div>;
}
