'use client';
import {useState} from 'react';
import {LogOut,ShieldCheck} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {createClient} from '@/lib/supabase/client';
import {Choice} from './shared';
import type {FitnessData,Profile} from '@/lib/fitness/model';
import {displayWeight,toKg} from '@/lib/fitness/domain';
import {validateNewPassword} from '@/lib/fitness/password';
import type {FitnessStore} from './use-fitness';

export const goals=['Perder gordura','Ganhar massa','Aumentar força','Recomposição corporal'];

export function ProfilePage({data,email,mutate}:{data:FitnessData;email:string;mutate:FitnessStore['mutate']}){
 const p=data.profile;const update=(patch:Partial<Profile>)=>mutate('profile',{...p,...patch});
 const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [current,setCurrent]=useState('');const [nonce,setNonce]=useState('');const [securityMessage,setSecurityMessage]=useState('');const [securityBusy,setSecurityBusy]=useState(false);
 const changePassword=async()=>{const issue=validateNewPassword(password,confirm);if(issue){setSecurityMessage(issue);return;}setSecurityBusy(true);const {error}=await createClient().auth.updateUser({password,...(current?{current_password:current}:{}),...(nonce?{nonce}:{})});setSecurityBusy(false);if(error){setSecurityMessage(error.code==='reauthentication_needed'?'Confirme sua identidade por e-mail e informe o código recebido.':'Não foi possível alterar a senha. Confira a senha atual ou use “Esqueci minha senha”.');return;}setPassword('');setConfirm('');setCurrent('');setNonce('');setSecurityMessage('Senha alterada com sucesso.');};
 const requestNonce=async()=>{const {error}=await createClient().auth.reauthenticate();setSecurityMessage(error?'Não foi possível enviar o código agora.':'Código enviado ao seu e-mail. Informe abaixo para alterar a senha.');};
 const signOut=async()=>{await createClient().auth.signOut();window.location.assign('/');};
 return <>
  <div className="page-heading"><div><div className="eyebrow">DO SEU JEITO</div><h1>Perfil</h1><p>Seus objetivos e preferências de treino.</p></div></div>
  <div className="profile-layout">
   <section className="card profile-card">
    <div className="profile-identity"><div className="avatar large">{p.name.slice(0,1).toUpperCase()}</div><div><h2>{p.name}</h2><p>{email}</p><span className="small lime"><ShieldCheck size={14} className="inline-icon"/>Conta protegida pelo Supabase</span></div></div>
    <div className="form-grid"><label>Nome<input defaultValue={p.name} maxLength={80} onBlur={e=>{const name=e.target.value.trim();if(name)update({name});else e.target.value=p.name;}}/></label><label>Altura (cm)<input type="number" min={80} max={250} defaultValue={p.height??''} onBlur={e=>{const n=Number(e.target.value);if(!e.target.value)update({height:null});else if(n>=80&&n<=250)update({height:n});else e.target.value=String(p.height??'');}}/></label><label>Peso atual ({p.unit})<input type="number" min={p.unit==='kg'?20:44} max={p.unit==='kg'?500:1102} step="0.1" defaultValue={p.weight?displayWeight(p.weight,p.unit).toFixed(1):''} onBlur={e=>{const n=Number(e.target.value);const kg=toKg(n,p.unit);if(!e.target.value)update({weight:null});else if(kg>=20&&kg<=500)update({weight:kg});else e.target.value=p.weight?displayWeight(p.weight,p.unit).toFixed(1):'';}}/></label></div>
    <h3>O que você quer conquistar?</h3><div className="goal-options">{goals.map(g=><label key={g}><Checkbox checked={p.goals.includes(g)} onCheckedChange={checked=>update({goals:checked?[...p.goals,g]:p.goals.filter(x=>x!==g)})}/>{g}</label>)}</div>
   </section>
   <section className="card preferences-card"><h2>Preferências</h2><div className="preference"><div><strong>Unidade de carga</strong><p>Conversão automática dos registros.</p></div><Choice label="Unidade de carga" value={p.unit} onChange={unit=>update({unit:unit as 'kg'|'lb'})} options={[{value:'kg',label:'kg'},{value:'lb',label:'lb'}]}/></div><div className="preference"><div><strong>Descanso padrão</strong><p>Para novos exercícios nas rotinas.</p></div><Choice label="Descanso padrão" value={String(p.rest)} onChange={rest=>update({rest:Number(rest)})} options={[30,45,60,90,120,150,180,240,300].map(v=>({value:String(v),label:`${v}s`}))}/></div><div className="preference"><div><strong>Meta semanal</strong><p>Quantidade de treinos na semana.</p></div><Choice label="Meta semanal" value={String(p.weeklyGoal)} onChange={v=>update({weeklyGoal:Number(v)})} options={[1,2,3,4,5,6,7].map(v=>({value:String(v),label:`${v} treinos`}))}/></div><div className="preference"><div><strong>Tema escuro</strong><p>Mais conforto durante o treino.</p></div><Switch aria-label="Tema escuro" checked={p.theme==='dark'} onCheckedChange={v=>update({theme:v?'dark':'light'})}/></div></section>
   <section className="card profile-card"><h2>Treino</h2><div className="preference"><div><strong>Nível</strong></div><Choice label="Nível de treino" value={p.level??'iniciante'} onChange={level=>update({level:level as Profile['level']})} options={[{value:'iniciante',label:'Iniciante'},{value:'intermediario',label:'Intermediário'},{value:'avancado',label:'Avançado'}]}/></div><label>Duração preferida (minutos)<input type="number" min={20} max={180} defaultValue={p.preferredDuration??''} onBlur={e=>{const v=Number(e.target.value);if(!e.target.value)update({preferredDuration:undefined});else if(v>=20&&v<=180)update({preferredDuration:v});else e.target.value=String(p.preferredDuration??'');}}/></label><p>Dias preferidos</p><div className="goal-options">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((day,index)=><label key={day}><Checkbox checked={p.preferredDays?.includes(index)??false} onCheckedChange={checked=>update({preferredDays:checked?[...new Set([...(p.preferredDays??[]),index])].sort():(p.preferredDays??[]).filter(d=>d!==index)})}/>{day}</label>)}</div><label>Equipamentos disponíveis (separe por vírgula)<input defaultValue={(p.availableEquipment??[]).join(', ')} onBlur={e=>update({availableEquipment:e.target.value.split(',').map(x=>x.trim().slice(0,60)).filter(Boolean).slice(0,30)})}/></label><label>Preferências<textarea maxLength={1500} value={p.preferences??''} onChange={e=>update({preferences:e.target.value})}/></label><label>Limitações opcionais<textarea maxLength={1000} value={p.limitations??''} onChange={e=>update({limitations:e.target.value})}/></label></section>
   <section className="card preferences-card"><h2>Segurança</h2><p>Seu e-mail: {email}. A senha é gerenciada pelo Supabase Auth.</p><label>Senha atual (quando solicitada)<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>Nova senha (mínimo 8 caracteres)<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="primary" disabled={securityBusy} onClick={changePassword}>Alterar senha</button><button className="text-button" onClick={requestNonce}>Enviar código de confirmação</button><label>Código recebido por e-mail<input inputMode="numeric" value={nonce} onChange={e=>setNonce(e.target.value.trim())}/></label><a href="/reset-password">Esqueci minha senha</a>{securityMessage&&<p role="status">{securityMessage}</p>}<h3>IA e privacidade</h3><p>Ao usar o gerador ou ler uma ficha por imagem, seus objetivos, preferências e o conteúdo enviado são processados pelo Gemini para gerar a resposta. Fotos não são armazenadas pelo aplicativo.</p></section>
  </div>
  <button className="text-button signout" onClick={signOut}><LogOut size={17}/>Sair da conta</button>
  <p><a className="secondary" href="/trainer">Personal e alunos</a></p>
 </>;
}
