'use client';
import {useState} from 'react';
import {Activity,Check} from 'lucide-react';
import {Choice,Modal} from './shared';
import {localDate} from '@/lib/fitness/domain';
import {newId,sessionSchema,type Session} from '@/lib/fitness/model';

const presets=['Futebol','Caminhada','Corrida','Ciclismo','Natação','Outro'];
const nowTime=()=>new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});

export function QuickActivity({onClose,onSave}:{onClose:()=>void;onSave:(session:Session)=>void}){
 const [kind,setKind]=useState('Futebol');const [custom,setCustom]=useState('');const [date,setDate]=useState(localDate());const [time,setTime]=useState(nowTime());const [duration,setDuration]=useState(60);const [effort,setEffort]=useState('7');const [notes,setNotes]=useState('');const [error,setError]=useState('');
 const name=kind==='Outro'?custom.trim():kind;
 function save(){setError('');if(!name){setError('Informe o nome da atividade.');return;}if(duration<1||duration>600){setError('A duração deve ficar entre 1 e 600 minutos.');return;}const started=new Date(`${date}T${time}:00`);if(Number.isNaN(started.getTime())){setError('Confira a data e o horário.');return;}const finished=new Date(started.getTime()+duration*60000);const exerciseId=newId();const session:Session={id:newId(),routineId:null,name,startedAt:started.toISOString(),finishedAt:finished.toISOString(),status:'completed',notes,isDemo:false,exercises:[{id:newId(),exercise:{id:exerciseId,name,muscle:'Condicionamento',secondary:'Corpo inteiro',equipment:'Atividade',notes:''},plan:{id:newId(),exerciseId,sets:1,minReps:1,maxReps:1,rest:0,notes,targetType:'minutes',targetText:`${duration} min`,suggestedWeight:0,loadText:''},sets:[{id:newId(),weight:0,reps:duration,rir:null,rpe:Number(effort),type:'normal',status:'completed',notes:'',completedAt:finished.toISOString()}]}]};const parsed=sessionSchema.safeParse(session);if(!parsed.success){setError(parsed.error.issues[0].message);return;}onSave(parsed.data);}
 return <Modal open title="Registrar outra atividade" description="Registre futebol, caminhada ou qualquer atividade que não esteja nas suas rotinas." onClose={onClose}><div className="quick-activity-icon"><Activity size={24}/></div><div className="quick-activity-form"><label>Atividade<Choice label="Tipo de atividade" value={kind} onChange={setKind} options={presets}/></label>{kind==='Outro'&&<label>Nome da atividade<input autoFocus maxLength={80} value={custom} onChange={event=>setCustom(event.target.value)} placeholder="Ex.: Vôlei, trilha, funcional"/></label>}<div className="form-grid"><label>Data<input type="date" value={date} max={localDate()} onChange={event=>setDate(event.target.value)}/></label><label>Horário<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><div className="form-grid"><label>Duração (min)<input type="number" min={1} max={600} value={duration} onChange={event=>setDuration(Number(event.target.value))}/></label><label>Esforço percebido<Choice label="Esforço percebido" value={effort} onChange={setEffort} options={[{value:'3',label:'Leve · RPE 3'},{value:'5',label:'Moderado · RPE 5'},{value:'7',label:'Intenso · RPE 7'},{value:'9',label:'Muito intenso · RPE 9'}]}/></label></div><label>Observações<textarea rows={3} maxLength={2000} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Ex.: futebol society, intensidade alta, sem dor"/></label></div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" onClick={save}><Check size={17}/>Salvar no histórico</button></div></Modal>;
}
