'use client';
import type {ReactNode} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {ArrowUpRight,Dumbbell} from 'lucide-react';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v} value={v}>{typeof o==='string'?o:o.label}</SelectItem>;})}</SelectContent></Select>;}
export function Modal({title,description,open,onClose,children,wide=false}:{title:string;description:string;open:boolean;onClose:()=>void;children:ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={o=>{if(!o)onClose();}}><DialogContent className={`fitness-modal ${wide?'wide':''}`}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>;}
export function Confirm({open,title,description,onClose,onConfirm,action='Excluir'}:{open:boolean;title:string;description:string;onClose:()=>void;onConfirm:()=>void;action?:string}){return <AlertDialog open={open} onOpenChange={o=>{if(!o)onClose();}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Voltar</AlertDialogCancel><AlertDialogAction onClick={onConfirm}>{action}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>;}
export function EmptyState({title,description,children}:{title:string;description:string;children?:ReactNode}){return <Empty className="empty-state"><EmptyHeader><Dumbbell size={30}/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>;}
export function SectionTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="section-heading"><h2>{title}</h2>{action&&<button className="text-button" onClick={onClick}>{action}<ArrowUpRight size={16}/></button>}</div>;}
