'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {fitnessDataSchema,resourceSchemas,type Entity,type FitnessData,type Resource} from '@/lib/fitness/model';
import {toast} from 'sonner';
type Pending={resource:Resource;id:string;entity:Entity;remove?:boolean;version:number;stamp:number};
type SaveState='loading'|'saved'|'saving'|'offline'|'error';
const keyMap={exercise:'exercises',routine:'routines',session:'sessions',measurement:'measurements'} as const;
function apply(data:FitnessData,p:Pending):FitnessData{if(p.resource==='profile')return {...data,profile:p.entity as FitnessData['profile']};const key=keyMap[p.resource];const list=data[key].filter(e=>e.id!==p.id);return {...data,[key]:p.remove?list:[...list,p.entity]};}
export function useFitness(uid:string){
 const [data,setData]=useState<FitnessData|null>(null);const [status,setStatus]=useState<SaveState>('loading');const [error,setError]=useState('');const [online,setOnline]=useState(true);const [conflict,setConflict]=useState(false);const [localSafe,setLocalSafe]=useState(true);
 const dataRef=useRef<FitnessData|null>(null),pending=useRef<Pending[]>([]),busy=useRef(false),blocked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);const storageKey=`personal-fitness-pending:${uid}`,snapshotKey=`personal-fitness-data:${uid}`;
 const storeSnapshot=useCallback((next:FitnessData)=>{try{localStorage.setItem(snapshotKey,JSON.stringify(next));setLocalSafe(true);return true;}catch{setLocalSafe(false);return false;}},[snapshotKey]);
 const storePending=useCallback(()=>{try{localStorage.setItem(storageKey,JSON.stringify(pending.current));setLocalSafe(true);return true;}catch{setLocalSafe(false);setError('Não foi possível manter uma cópia neste aparelho. Mantenha a página aberta até salvar.');return false;}},[storageKey]);
 const flush=useCallback(async()=>{if(busy.current||blocked.current||!dataRef.current)return;if(!navigator.onLine){setStatus('offline');return;}busy.current=true;
 try{while(pending.current.length){setStatus('saving');const item={...pending.current[0]};const response=await fetch('/api/fitness',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const result=await response.json() as {version?:number;error?:string};if(!response.ok){if(response.status===409){blocked.current=true;setConflict(true);}if(response.status===400||response.status===401)blocked.current=true;throw new Error(result.error??'Erro ao salvar.');}const version=result.version??0;dataRef.current={...dataRef.current!,versions:{...dataRef.current!.versions,[item.id]:version}};const current=pending.current.find(p=>p.id===item.id);if(current?.stamp===item.stamp)pending.current=pending.current.filter(p=>p.id!==item.id);else if(current)current.version=version;storePending();storeSnapshot(dataRef.current);setData({...dataRef.current});}setStatus('saved');setError('');}catch(e){setStatus(navigator.onLine?'error':'offline');setError(e instanceof Error?e.message:'Erro ao salvar.');}finally{busy.current=false;}},[storePending,storeSnapshot]);
 const load=useCallback(async()=>{setStatus('loading');try{const r=await fetch('/api/fitness',{cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'Entre novamente para abrir seus treinos.':'Não foi possível carregar. Tente novamente.');let next=await r.json() as FitnessData;let local:Pending[]=[];try{local=JSON.parse(localStorage.getItem(storageKey)??'[]');if(!Array.isArray(local))local=[];}catch{local=[];}pending.current=local;for(const p of local)next=apply(next,p);dataRef.current=next;setData(next);storeSnapshot(next);blocked.current=false;setStatus(local.length?'saving':'saved');setError('');if(local.length)void flush();}catch(e){try{const cached=fitnessDataSchema.safeParse(JSON.parse(localStorage.getItem(snapshotKey)??'null'));if(cached.success){dataRef.current=cached.data;setData(cached.data);setOnline(false);setStatus('offline');setError('Sem conexão. Seus dados salvos neste aparelho continuam disponíveis e serão sincronizados depois.');return;}}catch{}setStatus('error');setError(e instanceof Error?e.message:'Falha ao carregar.');}},[storageKey,snapshotKey,flush,storeSnapshot]);
 useEffect(()=>{void load();const onOnline=()=>{setOnline(true);void flush();};const onOffline=()=>{setOnline(false);if(pending.current.length)setStatus('offline');};const before=(e:BeforeUnloadEvent)=>{if(pending.current.length){e.preventDefault();e.returnValue='';}};window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);window.addEventListener('beforeunload',before);const retry=setInterval(()=>{if(pending.current.length)void flush();},10000);return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);window.removeEventListener('beforeunload',before);clearInterval(retry);};},[load,flush]);
 const mutate=useCallback((resource:Resource,entity:Entity,remove=false)=>{if(!dataRef.current)return;const parsed=resourceSchemas[resource].safeParse(entity);if(!remove&&!parsed.success){toast.error(parsed.error.issues[0]?.message??'Confira os campos.');return;}const existing=pending.current.find(p=>p.id===entity.id);const p:Pending={resource,entity,id:entity.id,remove,version:existing?.version??dataRef.current.versions[entity.id]??0,stamp:Date.now()+Math.random()};pending.current=existing?pending.current.map(x=>x.id===entity.id?p:x):[...pending.current,p];dataRef.current=apply(dataRef.current,p);setData(dataRef.current);storePending();storeSnapshot(dataRef.current);setStatus(navigator.onLine?'saving':'offline');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),450);},[flush,storePending,storeSnapshot]);
 const resolveConflict=useCallback(async()=>{try{const response=await fetch('/api/fitness',{cache:'no-store'});if(!response.ok)throw new Error('Não foi possível buscar a versão salva.');const server=await response.json() as FitnessData;for(const p of pending.current)p.version=server.versions[p.id]??0;let merged=server;for(const p of pending.current)merged=apply(merged,p);dataRef.current=merged;setData(merged);storePending();storeSnapshot(merged);blocked.current=false;setConflict(false);void flush();}catch(e){setError(e instanceof Error?e.message:'Erro ao resolver conflito.');}},[flush,storePending,storeSnapshot]);
 return {data,status,error,online,localSafe,conflict,resolveConflict,mutate,retry:flush,reload:load};
}
export type FitnessStore=ReturnType<typeof useFitness>;
